return {
  ["numToStr/Comment.nvim"] = { disable = true },
  ["goolord/alpha-nvim"] = { disable = true },
  ["max397574/better-escape.nvim"] = { disable = true },
  ["famiu/bufdelete.nvim"] = { disable = true },
  ["declancm/cinnamon.nvim"] = { disable = true },
  ["lukas-reineke/indent-blankline.nvim"] = { disable = true },
  ["p00f/clangd_extensions.nvim"] = require "user.plugins.clangd_extensions",
  ["hrsh7th/cmp-calc"] = require "user.plugins.cmp-calc",
  ["hrsh7th/cmp-emoji"] = require "user.plugins.cmp-emoji",
  ["kdheepak/cmp-latex-symbols"] = require "user.plugins.cmp-latex-symbols",
  ["jc-doyle/cmp-pandoc-references"] = require "user.plugins.cmp-pandoc-references",
  ["lukas-reineke/headlines.nvim"] = require "user.plugins.headlines",
  ["phaazon/hop.nvim"] = require "user.plugins.hop",
  ["echasnovski/mini.nvim"] = require "user.plugins.mini",
  ["jbyuki/nabla.nvim"] = require "user.plugins.nabla",
  ["danymat/neogen"] = require "user.plugins.neogen",
  ["EdenEast/nightfox.nvim"] = require "user.plugins.nightfox",
  ["mfussenegger/nvim-dap"] = require "user.plugins.dap",
  ["rcarriga/nvim-dap-ui"] = require "user.plugins.dapui",
  ["ethanholz/nvim-lastplace"] = require "user.plugins.nvim-lastplace",
  ["mtikekar/nvim-send-to-term"] = require "user.plugins.nvim-send-to-term",
  ["nvim-treesitter/nvim-treesitter-textobjects"] = require "user.plugins.nvim-treesitter-textobjects",
  ["nanotee/sqls.nvim"] = require "user.plugins.sqls",
  ["ziontee113/syntax-tree-surfer"] = require "user.plugins.syntax-tree-surfer",
  ["nvim-telescope/telescope-bibtex.nvim"] = require "user.plugins.telescope-bibtex",
  ["nvim-telescope/telescope-file-browser.nvim"] = require "user.plugins.telescope-file-browser",
  ["nvim-telescope/telescope-hop.nvim"] = require "user.plugins.telescope-hop",
  ["nvim-telescope/telescope-media-files.nvim"] = require "user.plugins.telescope-media-files",
  ["nvim-telescope/telescope-project.nvim"] = require "user.plugins.telescope-project",
  ["jose-elias-alvarez/typescript.nvim"] = require "user.plugins.typescript",
  ["vitalk/vim-simple-todo"] = require "user.plugins.vim-simple-todo",
  ["dhruvasagar/vim-table-mode"] = require "user.plugins.vim-table-mode",
  ["wakatime/vim-wakatime"] = require "user.plugins.vim-wakatime",
  ["folke/zen-mode.nvim"] = require "user.plugins.zen-mode",
  ["mickael-menu/zk-nvim"] = require "user.plugins.zk",
}
